### ISSUE TITLE
Administrative Access

### ISSUE THREAD

**Issue by DLu** [ros/urdf_sim_tutorial#12]
I am the maintainer of this package, but I do not have admin access to this repository. I would like to be able to change the default branch.

**Comment by clalancette** [comment]
I've just added you as an admin.

**Comment by DLu** [comment]
Thanks! Could I please get https://github.com/ros/urdf_tutorial/ too?

**Comment by clalancette** [comment]
> Thanks! Could I please get https://github.com/ros/urdf_tutorial/ too?

Done now.
