### ISSUE TITLE
Controller Spawner couldn't find the expected controller_manager ROS interface

### ISSUE THREAD

**Issue by blubbi321** [ros/urdf_sim_tutorial#5]
While trying to bring up a Gazebo simulation for my own robot I came across this tutorial. However for both of them I have the same issue:

When running `roslaunch urdf_sim_tutorial 13-diffdrive.launch` at some point there is

```[WARN] [1580815600.480090, 28.275000]: Controller Spawner couldn't find the expected controller_manager ROS interface.```

The robot is shown correctly in Gazebo at first, then it retracts the gripper inside its body (which I guess is not intended) and the controls dont work.

It might be a namespace issue according to https://answers.ros.org/question/218373/controller-spawner-couldnt-find-the-expected-controller_manager-ros-interface/

However, I wasnt able to fix it so far (working in ros kinetic). Any ideas?

**Comment by blubbi321** [comment]
Ok apparently I was missing required packages. I did something similar to `sudo apt-get install ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control ros-kinetic-ros-controllers` and now controlling it kinda seems to work

**Comment by DLu** [comment]
For future reference, how did you install/clone urdf_sim_tutorial?
