### ISSUE TITLE
Error in launching URDF sim tutorials

### ISSUE THREAD

**Issue by qboticslabs** [ros/urdf_sim_tutorial#7]
Hello

 Attaching the error when we launch the urdf_sim_tutorials launch file for noetic testing version

/usr/bin/env: ‘python’: No such file or directory
RLException: while processing /opt/ros/noetic/share/urdf_sim_tutorial/launch/gazebo.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/share/xacro/xacro.py', '/opt/ros/noetic/share/urdf_sim_tutorial/urdf/09-publishjoints.urdf.xacro']] returned with code [127]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro.py $(arg model)"/>
The traceback for the exception was written to the log file

Regards

**Comment by DLu** [comment]
This seems more like a [xacro](https://github.com/ros/xacro) problem. What OS are you running?

**Comment by qboticslabs** [comment]
Hi @DLu 
I am using Ubuntu 20.04

**Comment by DLu** [comment]
What happens when you `rosrun xacro xacro.py`?

**Comment by qboticslabs** [comment]
Same error
/usr/bin/env: ‘python’: No such file or directory

**Comment by qboticslabs** [comment]
@DLu  seems like in xacro.py, the shebang is not changed.

Its still 

#! /usr/bin/env python

**Comment by DLu** [comment]
[I believe that is correct though](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs)

**Comment by DLu** [comment]
What happens if you type `/usr/bin/env python` into your terminal?

**Comment by qboticslabs** [comment]
/usr/bin/env: ‘python’: No such file or directory

**Comment by DLu** [comment]
Ok, I opened up an issue with `xacro`, we'll track it from there.

**Comment by qboticslabs** [comment]
The tutorials are working if I change the shebang to 

#! /usr/bin/env python3   in xacro.py


Please have a look.
