### ISSUE TITLE
How to get gazebo.launch to work properly at install?

### ISSUE THREAD

**Issue by jahad9819jjj** [ros/urdf_sim_tutorial#9]
Hello... I'm a user from the ROS Melodic era.
Today, I installed Noetic on my OS and ran 
```
roslaunch urdf_sim_tutorial 09-joints.launch
```
 Then, I got the following error.

```
RLException: while processing /opt/ros/noetic/share/urdf_sim_tutorial/launch/gazebo.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: no such command [['/opt/ros/noetic/share/xacro/xacro.py', '/opt/ros/noetic/share/urdf_sim_tutorial/urdf/09-publishjoints.urdf.xacro']]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro.py $(arg model)"/>
The traceback for the exception was written to the log file

```

 I know how to fix around this and this worked well, but I don't think it is reflected when I install Noetic by `sudo apt install`.  It's too much work to rewrite `gazebo.launch` every time I install Noetic. I would like to help if I can.

**Comment by DLu** [comment]
This was fixed in #8 but it hasn't been released yet. I'll do that now.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/25172

**Comment by jahad9819jjj** [comment]
There already be the issue but I didn't know how to reflect latest master branch to `apt`. However, you already done this just minutes ago😊 Thanks!

**Comment by jahad9819jjj** [comment]
@DLu There already be the issue but I didn't know how to reflect latest master branch to `apt`. However, you already done this just minutes ago😊 Thanks!
